services:
  to-do:
    env_file:
      - ./1. to-do list/.env
    build:
      context: ./1. to-do list/
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
  blog:
    env_file:
      - ./2. blog/.env
    build:
      context: ./2. blog/
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
  snake:
    build:
      context: ./3. snake/
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
