services:
  to-do:
    env_file:
      - ./1. to-do list/.env
    build:
      context: ./1. to-do list/
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./1. to-do list/
        target: /app
      - type: volume
        target: /app/node_modules
  blog:
    env_file:
      - ./2. blog/.env
    build:
      context: ./2. blog/
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./2. blog/
        target: /app
      - type: volume
        target: /app/node_modules
  snake:
    build:
      context: ./3. snake/
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./3. snake/
        target: /app
      - type: volume
        target: /app/node_modules
